name: tasks-app
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: lazar
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    #   # - MONGO_INITDB_ROOT_USERNAME=lazar
    env_file:
      - ./env/mongo.env
    # networks:
    #   - challenge-network
  backend:
    build: ./backend
    ports:
      - '3000:80'
      # - ''
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules    
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend 
    ports:
      - '3100:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
